title: 生活 技术 心情
layout: default
show_downloads: false
header-img: image/header-img.jpg
email: honeytrry@gmail.com
twitter_username: honeytrry
github_username:  honeytrry

# Sidebar settings
sidebar: true    #whether or not using siderbar
sidebar-about-description: "just a try"

# Build settings
markdown: kramdown

cateory: web
#gems: [jekyll-paginate]
paginate: 5
#paginate_path: "page:num"


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页

#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
